controller_manager:
  ros__parameters:
    update_rate: 100

    # 팔 컨트롤러 상세 설정
    xarm_1s_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # 그리퍼 컨트롤러 상세 설정
    hand_controller:
      type: position_controllers/GripperActionController

    # joint_states 토픽 뿌려주기
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

xarm_1s_arm_controller:
  ros__parameters:
    joints:
      - arm6
      - arm5
      - arm4
      - arm3
      - arm2

    # position 명령을 보내기
    command_interfaces:
      - position

    # position 명령을 받기
    state_interfaces:
      - position

    # 현재 joint 상태를 보면서 제어 (닫힌 루프)
    open_loop_control: false

    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

hand_controller:
  ros__parameters:
    joint: arm1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
